//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace GameLogic {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("GameLogic.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [
        ///	{
        ///		&quot;TemplateID&quot; : &quot;Wall&quot;,
        ///		&quot;Angle&quot; : 0,
        ///		&quot;Components&quot;: [
        ///			{
        ///				&quot;ComponentType&quot; : &quot;VisualComponent&quot;,
        ///				&quot;AnchorX&quot; : 0,
        ///				&quot;AnchorY&quot; : 0,
        ///				&quot;Alpha&quot; : 255,
        ///				&quot;Width&quot; : 64,
        ///				&quot;Height&quot; : 64,
        ///				&quot;Sprites&quot; :[
        ///					{
        ///						&quot;FramesPerSecond&quot; : 0,
        ///						&quot;Looped&quot; : false,
        ///						&quot;X&quot; : 0,
        ///						&quot;Y&quot; : 0,
        ///						&quot;Width&quot; : 128,
        ///						&quot;Height&quot; : 128,
        ///						&quot;NumberOfFrames&quot; : 0,
        ///						&quot;TexturePath&quot; : &quot;Resources\\Wall.png&quot;,
        ///						&quot;Name&quot; : &quot;Wall&quot;
        ///					}
        ///				]
        ///			}
        ///		]
        ///	},
        ///	{
        ///		&quot;Tem [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UbisoftTemplatesJSON {
            get {
                return ResourceManager.GetString("UbisoftTemplatesJSON", resourceCulture);
            }
        }
    }
}
